// aiagentfe-vue/src/components/AppHeader.vue
<template>
  <header class="app-header">
    <div class="header-left">
      <span class="logo" @click="goToConversations">简历优化助手</span>
      <nav class="header-nav">
        <span
          class="nav-link"
          :class="{ active: $route.path === '/conversations' }"
          @click="goToConversations"
          >会话</span
        >
        <span
          class="nav-link"
          :class="{ active: $route.path === '/documents' }"
          @click="goToDocuments"
          >知识库</span
        >
      </nav>
    </div>
    <div class="header-right">
      <span class="user-phone">{{ store.userInfo?.phone || '' }}</span>
      <el-button type="danger" size="small" @click="handleLogout"> 退出登录 </el-button>
    </div>
  </header>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { useResumeStore } from '@/stores/resume'
import { logout } from '@/api'

const router = useRouter()
const store = useResumeStore()

onMounted(() => {
  store.fetchUserProfile()
})

function goToConversations() {
  router.push('/conversations')
}

function goToDocuments() {
  router.push('/documents')
}

async function handleLogout() {
  try {
    await logout()
  } catch {
    // 即使服务端失败也清除本地
  }
  localStorage.removeItem('auth_token')
  localStorage.removeItem('login_phone')
  ElMessage.success('已退出登录')
  router.push('/')
}
</script>

<style scoped>
.app-header {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  height: 50px;
  background: #fff;
  border-bottom: 1px solid #e5e5e5;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 20px;
  z-index: 1000;
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.06);
}

.header-left {
  display: flex;
  align-items: center;
}

.header-left .logo {
  font-size: 16px;
  font-weight: 600;
  color: #409eff;
  cursor: pointer;
}

.header-left .logo:hover {
  color: #66b1ff;
}

.header-nav {
  display: flex;
  gap: 16px;
  margin-left: 24px;
}

.nav-link {
  font-size: 14px;
  color: #666;
  cursor: pointer;
  padding: 4px 8px;
  border-radius: 4px;
  transition: all 0.2s;
}

.nav-link:hover {
  color: #409eff;
  background: #f0f7ff;
}

.nav-link.active {
  color: #409eff;
  font-weight: 500;
}

.header-right {
  display: flex;
  align-items: center;
  gap: 12px;
}

.user-phone {
  font-size: 13px;
  color: #666;
}
</style>

// aiagentfe-react/src/components/AppHeader.tsx
import { useEffect } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import { Button, message } from 'antd'
import { LogoutOutlined } from '@ant-design/icons'
import { useResumeStore } from '@/stores/resume'
import { logout } from '@/api'

export default function AppHeader() {
  const navigate = useNavigate()
  const location = useLocation()
  const userInfo = useResumeStore((s) => s.userInfo)
  const fetchUserProfile = useResumeStore((s) => s.fetchUserProfile)

  useEffect(() => {
    fetchUserProfile()
  }, [fetchUserProfile])

  const handleLogout = async () => {
    try {
      await logout()
    } catch {
      /* empty */
    }
    localStorage.removeItem('auth_token')
    localStorage.removeItem('login_phone')
    window.dispatchEvent(new Event('auth-change'))
    message.success('已退出登录')
    navigate('/')
  }

  return (
    <header className="fixed top-0 left-0 right-0 h-[50px] bg-white border-b border-[#e5e5e5] flex items-center justify-between px-5 z-[1000] shadow-[0_1px_4px_rgba(0,0,0,0.06)]">
      <div className="flex items-center gap-6">
        <span
          className="text-base font-semibold text-[#1677ff] cursor-pointer"
          onClick={() => navigate('/conversations')}
        >
          简历优化助手
        </span>
        <nav className="flex gap-4">
          <span
            className={`text-sm cursor-pointer px-2 py-0.5 rounded transition-all ${
              location.pathname === '/conversations'
                ? 'text-[#1677ff] font-medium'
                : 'text-[#666] hover:text-[#1677ff] hover:bg-[#f0f7ff]'
            }`}
            onClick={() => navigate('/conversations')}
          >
            会话
          </span>
          <span
            className={`text-sm cursor-pointer px-2 py-0.5 rounded transition-all ${
              location.pathname === '/documents'
                ? 'text-[#1677ff] font-medium'
                : 'text-[#666] hover:text-[#1677ff] hover:bg-[#f0f7ff]'
            }`}
            onClick={() => navigate('/documents')}
          >
            知识库
          </span>
        </nav>
      </div>
      <div className="flex items-center gap-3">
        <span className="text-[13px] text-[#666]">{userInfo?.phone || ''}</span>
        <Button type="primary" danger size="small" icon={<LogoutOutlined />} onClick={handleLogout}>
          退出登录
        </Button>
      </div>
    </header>
  )
}
