// aiagentfe-vue/src/components/ModificationReview.vue
<template>
  <div class="modification-review">
    <div class="ref-docs-header">修改预览</div>
    <div class="modification-item">
      <div class="modification-header">
        <span
          ><strong>{{ item.field }}</strong></span
        >
        <div v-if="item.reason" class="mod-reason">{{ item.reason }}</div>
      </div>
      <div class="modification-content">
        <div class="mod-label">修改前：</div>
        <div class="mod-text original">
          <RenderSuggestion :text="item.current" />
        </div>
        <div class="mod-label">修改后：</div>
        <div class="mod-text modified">
          <RenderSuggestion :text="item.suggestion" />
        </div>
      </div>
      <div class="modification-actions">
        <el-button
          type="primary"
          size="small"
          :disabled="disabled"
          @click="$emit('accept', item, msgIndex, modIdx)"
        >
          接受
        </el-button>
        <el-button
          size="small"
          :disabled="disabled"
          @click="$emit('supplement', item, msgIndex, modIdx)"
        >
          补充
        </el-button>
        <el-button size="small" :disabled="disabled" @click="$emit('reject', msgIndex, modIdx)">
          拒绝
        </el-button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { ModificationItem } from '@/types/chat'
import RenderSuggestion from './RenderSuggestion.vue'

const props = defineProps<{
  item: ModificationItem
  msgIndex: number
  modIdx: number
  disabled?: boolean
}>()

defineEmits<{
  accept: [item: ModificationItem, msgIndex: number, modIdx: number]
  supplement: [item: ModificationItem, msgIndex: number, modIdx: number]
  reject: [msgIndex: number, modIdx: number]
}>()
</script>

<style scoped>
.modification-review {
  margin-top: 10px;
  padding-top: 10px;
  border-top: 1px dashed #e5e5e5;
}

.ref-docs-header {
  font-size: 12px;
  color: #999;
  margin-bottom: 8px;
}

.modification-item {
  font-size: 12px;
  color: #666;
  background: #f9f9f9;
  border-radius: 6px;
  margin-bottom: 8px;
  padding: 10px;
}

.modification-header {
  margin-bottom: 6px;
}

.mod-reason {
  color: #999;
  font-size: 11px;
  margin-top: 2px;
}

.modification-content {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.mod-label {
  color: #999;
  font-size: 11px;
}

.mod-text {
  color: #333;
  line-height: 1.4;
  white-space: pre-wrap;
}

.mod-text.modified {
  background: #f0f7ff;
  padding: 8px;
  border-radius: 4px;
  border: 1px solid #d0e3ff;
  font-size: 12px;
}

.mod-text.original {
  background: #fff7f0;
  padding: 8px;
  border-radius: 4px;
  border: 1px solid #ffd0c8;
  font-size: 12px;
}

.modification-actions {
  display: flex;
  gap: 8px;
  margin-top: 8px;
}
</style>

// aiagentfe-react/src/components/ModificationReview.tsx
import { Button } from 'antd'
import type { ModificationItem } from '@/types/chat'
import RenderSuggestion from '@/lib/RenderSuggestion'

interface ModificationReviewProps {
  item: ModificationItem
  msgIndex: number
  modIdx: number
  disabled?: boolean
  onAccept: (item: ModificationItem, msgIndex: number, modIdx: number) => void
  onSupplement: (item: ModificationItem, msgIndex: number, modIdx: number) => void
  onReject: (msgIndex: number, modIdx: number) => void
}

export default function ModificationReview({
  item,
  msgIndex,
  modIdx,
  disabled,
  onAccept,
  onSupplement,
  onReject
}: ModificationReviewProps) {
  return (
    <div className="mt-2.5 pt-2.5 border-t border-dashed border-[#e5e5e5]">
      <div className="text-xs text-[#999] mb-2">修改预览</div>
      <div className="text-xs text-[#666] bg-[#f9f9f9] rounded-md mb-2 p-2.5">
        <div className="mb-1.5">
          <strong>{item.field}</strong>
          {item.reason && <div className="text-[#999] text-[11px] mt-0.5">{item.reason}</div>}
        </div>
        <div className="flex flex-col gap-1">
          <div className="text-[#999] text-[11px]">修改前：</div>
          <div className="text-[#333] leading-[1.4] bg-[#fff7f0] p-2 rounded border border-[#ffd0c8] text-[12px]">
            <RenderSuggestion text={item.current} />
          </div>
          <div className="text-[#999] text-[11px]">修改后：</div>
          <div className="text-[#333] leading-[1.4] bg-[#f0f7ff] p-2 rounded border border-[#d0e3ff] text-[12px]">
            <RenderSuggestion text={item.suggestion} />
          </div>
        </div>
        <div className="flex gap-2 mt-2">
          <Button
            type="primary"
            size="small"
            disabled={disabled}
            onClick={() => onAccept(item, msgIndex, modIdx)}
          >
            接受
          </Button>
          <Button
            size="small"
            disabled={disabled}
            onClick={() => onSupplement(item, msgIndex, modIdx)}
          >
            补充
          </Button>
          <Button size="small" disabled={disabled} onClick={() => onReject(msgIndex, modIdx)}>
            拒绝
          </Button>
        </div>
      </div>
    </div>
  )
}
