// aiagentfe-vue/src/components/OptimizationCard.vue
<template>
  <div class="ref-doc-item">
    <div class="ref-doc-header">
      <span
        ><strong>{{ item.field }}</strong> ({{ item.priority }})</span
      >
      <el-button type="primary" size="small" :disabled="disabled" @click="$emit('apply', item)">
        采纳
      </el-button>
    </div>
    <div v-if="item.reason" class="opt-reason">{{ item.reason }}</div>
    <div class="ref-doc-content">
      <div class="ref-doc-label">原文：</div>
      <div class="ref-doc-text original-text">
        <RenderSuggestion :text="item.current" />
      </div>
      <div class="ref-doc-label">建议：</div>
      <div class="ref-doc-text">
        <RenderSuggestion :text="item.suggestion" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { OptimizationItem } from '@/types/chat'
import RenderSuggestion from './RenderSuggestion.vue'

defineProps<{
  item: OptimizationItem
  disabled?: boolean
}>()

defineEmits<{
  apply: [item: OptimizationItem]
}>()
</script>

<style scoped>
.ref-doc-item {
  font-size: 12px;
  color: #666;
  background: #f9f9f9;
  border-radius: 6px;
  margin-bottom: 8px;
  padding: 10px;
}

.ref-doc-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 6px;
}

.opt-reason {
  color: #999;
  font-size: 11px;
  margin-bottom: 6px;
}

.ref-doc-content {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.ref-doc-label {
  color: #999;
  font-size: 11px;
}

.ref-doc-text {
  color: #333;
  line-height: 1.4;
  white-space: pre-wrap;
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.original-text {
  background: #fff7f0;
  padding: 8px;
  border-radius: 4px;
  border: 1px solid #ffd0c8;
  -webkit-line-clamp: initial;
  display: block;
}
</style>

// aiagentfe-react/src/components/OptimizationCard.tsx
import { Button } from 'antd'
import type { OptimizationItem } from '@/types/chat'
import RenderSuggestion from '@/lib/RenderSuggestion'

interface OptimizationCardProps {
  item: OptimizationItem
  disabled?: boolean
  onApply: (item: OptimizationItem) => void
}

export default function OptimizationCard({ item, disabled, onApply }: OptimizationCardProps) {
  return (
    <div className="text-xs text-[#666] bg-[#f9f9f9] rounded-md mb-2 p-2.5">
      <div className="flex justify-between items-center mb-1.5">
        <span>
          <strong>{item.field}</strong> ({item.priority})
        </span>
        <Button type="primary" size="small" disabled={disabled} onClick={() => onApply(item)}>
          采纳
        </Button>
      </div>
      {item.reason && <div className="text-[#999] text-[11px] mb-1.5">{item.reason}</div>}
      <div className="flex flex-col gap-1">
        <div className="text-[#999] text-[11px]">原文：</div>
        <div className="text-[#333] leading-[1.4] bg-[#fff7f0] p-2 rounded border border-[#ffd0c8] text-[12px] whitespace-pre-wrap">
          <RenderSuggestion text={item.current} />
        </div>
        <div className="text-[#999] text-[11px]">建议：</div>
        <div className="text-[#333] leading-[1.4] bg-[#e6f7ff] p-2 rounded border border-[#91d5ff] text-[12px] whitespace-pre-wrap">
          <RenderSuggestion text={item.suggestion} />
        </div>
      </div>
    </div>
  )
}
