// aiagentfe-react/src/pages/EditorPage.tsx
import { useState, useRef, useEffect, useCallback, useMemo } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { message, Skeleton, Result, Button } from 'antd'
import { Chat } from '@ai-sdk/react'
import { useResumeStore } from '@/stores/resume'
import PdfPreview from '@/components/PdfPreview'
import ChatPanel from '@/components/ChatPanel'
import ConversationDrawer from '@/components/ConversationDrawer'
import { MultipartChatTransport } from '@/lib/multipart-chat-transport'
import {
  getReferenceFiles, deleteReferenceFile, api, type ReferenceDoc, type DocVersion,
  getDocHistory, restoreDocVersion, getConversationMessages, renderResumePdf
} from '@/api'
import type { OptimizationItem, ModificationItem, Message } from '@/types/chat'

interface QueuedRequest {
  id: string
  type: 'search' | 'apply' | 'accept'
  label: string
  execute: () => void
  canceled: boolean
  timestamp: number
  status: 'pending' | 'processing' | 'completed' | 'failed'
  disabledKey?: string
  wasSupplement?: boolean
}

const MESSAGES_PAGE_SIZE = 100

function getLabel(type: string, payload?: any): string {
  if (type === 'search') return `发送消息：${payload?.text?.slice(0, 20) || '...'}`
  return type === 'apply' ? `采纳建议：${payload?.field || ''}` : `确认修改：${payload?.field || ''}`
}

const showReasoningMap = new Map<string, boolean>()

function extractPartsText(parts: any[]): string {
  return parts?.filter((p: any) => p.type === 'text' || p.type === 'text-delta')?.map((p: any) => p.text ?? '').filter(Boolean).join('\n') ?? ''
}

function extractPartsReasoning(parts: any[]): string {
  return parts?.filter((p: any) => p.type === 'reasoning' || p.type === 'reasoning-delta')?.map((p: any) => p.text ?? '').filter(Boolean).join('\n') ?? ''
}

function extractPartsOptimizations(parts: any[]): OptimizationItem[] {
  const list: OptimizationItem[] = []
  for (const part of parts?.filter((p: any) => p.type === 'tool-invocation' || p.type?.startsWith('tool-')) ?? []) {
    const output = part.output ?? part.result ?? part.toolInvocation?.result
    if (output?.optimization) list.push(output.optimization)
    if (output?.optimizations) list.push(...output.optimizations)
  }
  return list
}

function extractPartsModifications(parts: any[]): ModificationItem[] {
  const list: ModificationItem[] = []
  for (const part of parts?.filter((p: any) => p.type === 'tool-invocation' || p.type?.startsWith('tool-')) ?? []) {
    const output = part.output ?? part.result ?? part.toolInvocation?.result
    if (output?.modification) list.push(output.modification)
  }
  return list
}

function mapApiMessage(m: { id?: number | string; role: string; content: string; reasoning?: string }): Message {
  return {
    id: String(m.id ?? ''), role: m.role as 'user' | 'assistant', content: m.content,
    reasoning: m.reasoning || '', showReasoning: false, optimizations: [],
  }
}

export default function EditorPage() {
  const navigate = useNavigate()
  const { id: routeId } = useParams()
  const resumeStore = useResumeStore()

  const [pdfUrl, setPdfUrl] = useState('')
  const [conversationId, setConversationId] = useState('')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [drawerVisible, setDrawerVisible] = useState(false)
  const [messages, setMessages] = useState<Message[]>([])
  const [historyLoading, setHistoryLoading] = useState(false)
  const [messagesPage, setMessagesPage] = useState(1)
  const [hasMoreHistory, setHasMoreHistory] = useState(true)
  const [referenceFiles, setReferenceFiles] = useState<ReferenceDoc[]>([])
  const [chatError, setChatError] = useState('')
  const [failedMessage, setFailedMessage] = useState('')
  const [isStreaming, setIsStreaming] = useState(false)
  const [_pendingMods, setPendingMods] = useState<{ field: string; timestamp: number }[]>([])
  const [_refFilesLoading, setRefFilesLoading] = useState(false)
  const [_supplementCount, setSupplementCount] = useState(0)
  const [currentSupplementField, setCurrentSupplementField] = useState('')
  const [currentSupplementOriginal, setCurrentSupplementOriginal] = useState('')
  const [currentSupplementMsgIndex, setCurrentSupplementMsgIndex] = useState(-1)
  const [currentSupplementModIdx, setCurrentSupplementModIdx] = useState(-1)
  const [requestQueue, setRequestQueue] = useState<QueuedRequest[]>([])
  const [isProcessing, setIsProcessing] = useState(false)
  const [isSearchProcessing, setIsSearchProcessing] = useState(false)
  const [disabledOpts, setDisabledOpts] = useState<Set<string>>(new Set())
  const [disabledMods, setDisabledMods] = useState<Set<string>>(new Set())
  const [docVersions, setDocVersions] = useState<DocVersion[]>([])
  const [activeVersionIdx, setActiveVersionIdx] = useState(0)

  const autoScroll = useRef(true)
  const chatPanelRef = useRef<any>(null)
  const sdkSyncedIds = useRef(new Set<string>())
  const pendingModsRef = useRef<{ field: string; timestamp: number }[]>([])
  const chatRef = useRef<Chat<any> | null>(null)
  const unregRef = useRef<(() => void) | null>(null)
  const conversationIdRef = useRef(conversationId)
  useEffect(() => { conversationIdRef.current = conversationId }, [conversationId])

  const chatTitle = useMemo(() => resumeStore.conversationTitle || '简历优化助手', [resumeStore.conversationTitle])

  const transportRef = useRef<MultipartChatTransport<any> | null>(null)
  if (!transportRef.current) {
    transportRef.current = new MultipartChatTransport({
      fetch: async (input, init) => {
        const headers = new Headers(init?.headers)
        const token = localStorage.getItem('auth_token')
        if (token) headers.set('Authorization', `Bearer ${token}`)
        const phone = localStorage.getItem('login_phone')
        if (phone) headers.set('X-Phone', phone)
        return fetch(input, { ...init, headers })
      },
    })
  }

  const handleStop = useCallback(() => {
    transportRef.current?.stop()
    setRequestQueue([])
    setIsProcessing(false)
    setIsSearchProcessing(false)
  }, [])

  // ═══ initChat — 与 Vue line 651-801 对齐 ═══
  function initChat(historyMessages?: any[]) {
    unregRef.current?.()
    chatRef.current = new Chat({
      transport: transportRef.current!,
      ...(historyMessages?.length ? { messages: historyMessages } : {}),
      onError: (err: Error) => {
        console.error('Chat error:', err)
        if (err.message?.includes('reasoning-delta for missing reasoning part')) { dequeue(); return }
        pendingModsRef.current = []
        setPendingMods([])
        setChatError(err.message || '操作失败')
        setFailedMessage('')
        setIsStreaming(false)
        dequeue()
      },
      onFinish: async ({ messages: sdkMessages }: any) => {
        setIsStreaming(false)
        sdkMessages.forEach((msg: any) => { if (msg.id && !showReasoningMap.has(msg.id)) showReasoningMap.set(msg.id, false) })

        if (pendingModsRef.current.length > 0) {
          const pending = pendingModsRef.current[0]
          pendingModsRef.current = pendingModsRef.current.slice(1)
          setPendingMods((prev) => { if (prev.length === 0) return prev; return prev.slice(1) })
          setMessages((prev) => {
            const filtered = prev.filter((m) => {
              if (m.id?.startsWith('temp-')) return false
              if (m.role === 'assistant' && !m.content && !m.optimizations?.length && !m.modifications?.length) return false
              return true
            })
            return [...filtered,
              { id: `result-user-${Date.now()}`, role: 'user', content: `确认修改：${pending.field}` },
              { id: `result-status-${Date.now()}`, role: 'assistant', content: `正在处理「${pending.field}」...` },
              { id: `result-done-${Date.now()}`, role: 'assistant', content: '已采纳建议并生成修改内容' },
            ]
          })
          sdkMessages.forEach((m: any) => { if (m.id) sdkSyncedIds.current.add(m.id) })
          if (conversationIdRef.current) { reloadPdfFromServer(conversationIdRef.current); loadDocHistory(conversationIdRef.current) }
        }

        const newStoreMessages = sdkMessages.map((m: any) => {
          const existing = resumeStore.messages.find((sm: any) => sm.id === m.id)
          return {
            id: m.id ?? '', role: m.role as 'user' | 'assistant',
            content: extractPartsText(m.parts),
            reasoning: existing?.reasoning || extractPartsReasoning(m.parts) || '',
            optimizations: (existing as any)?.optimizations || extractPartsOptimizations(m.parts) || [],
            modifications: (existing as any)?.modifications || extractPartsModifications(m.parts) || [],
          }
        })
        useResumeStore.setState({ messages: newStoreMessages })
        scrollToBottom()
        dequeue()
      },
    })

    // 播种初始 SDK 消息 ID（Vue line 747-749）
    const im = chatRef.current?.messages ?? []
    im.forEach((m: any) => { if (m.id) sdkSyncedIds.current.add(m.id) })

    // ~registerMessagesCallback — 与 Vue watch(line 752-789) 对齐
    unregRef.current = (chatRef.current as any)['~registerMessagesCallback'](() => {
      const c = chatRef.current
      if (!c) return
      setIsStreaming(c.status === 'streaming')
      const sdkMsgs = c.messages ?? []
      if (!sdkMsgs.length) return

      // ① 清理过期 pendingMods
      if (pendingModsRef.current.length > 0) {
        setPendingMods((prev) => {
          const filtered = prev.filter((p) => Date.now() - p.timestamp < 60000)
          pendingModsRef.current = filtered
          return filtered
        })
        if (pendingModsRef.current.length > 0) return
      }

      // ② 新消息：sdkSyncedIds 去重 filter + map + append + mark
      const newSdk = sdkMsgs.filter((m: any) => m.id && !sdkSyncedIds.current.has(m.id))
      if (newSdk.length > 0) {
        const mapped = newSdk.map((m: any) => ({
          id: m.id, role: m.role as 'user' | 'assistant',
          content: extractPartsText(m.parts ?? []),
          reasoning: extractPartsReasoning(m.parts ?? []),
          showReasoning: showReasoningMap.get(m.id ?? '') ?? false,
          optimizations: extractPartsOptimizations(m.parts ?? []),
          modifications: extractPartsModifications(m.parts ?? []),
        }))
        newSdk.forEach((m: any) => { if (m.id) sdkSyncedIds.current.add(m.id) })
        setMessages((prev) => {
          const result = [...prev]
          for (const msg of mapped) {
            const localIdx = result.findIndex((m) => m.role === 'user' && m.id?.startsWith('local-restore-'))
            if (localIdx !== -1) { result[localIdx] = msg; continue }
            result.push(msg)
          }
          return result
        })
      }

      // ③ 最后一条消息：增量更新
      const lastSdk = sdkMsgs[sdkMsgs.length - 1]
      if (lastSdk?.id) {
        setMessages((prev) => prev.map((m) => {
            if (m.id !== lastSdk.id) return m
            const p = lastSdk.parts ?? []
            const cc = extractPartsText(p)
            const rr = extractPartsReasoning(p)
            const oo = extractPartsOptimizations(p)
            const mm = extractPartsModifications(p)
            return {
              ...m,
              ...(cc ? { content: cc } : {}),
              ...(rr ? { reasoning: rr } : {}),
              ...(oo.length ? { optimizations: oo } : {}),
              ...(mm.length ? { modifications: mm } : {}),
            }
          }))
      }

      if (autoScroll.current) scrollToBottom()
    }, 0)
  }

  // ═══ 队列系统 — 与 Vue 对齐 ═══
  const processQueue = useCallback(() => {
    setRequestQueue((prev) => {
      const trimmed = prev.filter((r) => !r.canceled)
      if (trimmed.length === 0) { setIsProcessing(false); setIsSearchProcessing(false); return trimmed }
      if (trimmed[0].status !== 'pending') return trimmed
      setIsProcessing(true)
      setIsSearchProcessing(trimmed[0].type === 'search')
      const execute = trimmed[0].execute
      const updated = trimmed.map((r) => r.id === trimmed[0].id ? { ...r, status: 'processing' as const } : r)
      setTimeout(() => { try { execute() } catch (err) { console.error('Queue execute error:', err); processQueue() } }, 0)
      return updated
    })
  }, [])

  const enqueueRequest = useCallback(
    (req: Omit<QueuedRequest, 'id' | 'timestamp' | 'status' | 'label' | 'canceled'>, payload?: any) => {
      if (payload?.field) {
        setRequestQueue((prev) => {
          const dupIdx = prev.findIndex((r) => r.status === 'pending' && r.type === req.type && r.label.includes(payload.field))
          if (dupIdx === -1) return prev
          const filtered = [...prev]; filtered.splice(dupIdx, 1); return filtered
        })
      }
      const newReq: QueuedRequest = {
        ...req, id: `req_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
        label: getLabel(req.type, payload), status: 'pending', canceled: false, timestamp: Date.now(),
      }
      setRequestQueue((prev) => [...prev, newReq])
      setTimeout(() => processQueue(), 0)
    },
    [processQueue]
  )

  // ═══ 辅助函数 ═══
  const loadReferenceFiles = useCallback(async (id?: string) => { const cid = id ?? conversationId; if (!cid) return; setRefFilesLoading(true); try { const r = await getReferenceFiles(cid); setReferenceFiles(r.docs || []) } catch (e) { console.error(e) } finally { setRefFilesLoading(false) } }, [conversationId])

  const loadDocHistory = useCallback(async (convId?: string) => {
    const cid = convId ?? conversationId; if (!cid) return
    try { const r = await getDocHistory(cid); setDocVersions(r.versions ?? []); setActiveVersionIdx(Math.max(0, (r.versions ?? []).length - 1)) } catch (e) { console.error(e) }
  }, [conversationId])

  const reloadPdfFromServer = useCallback(async (convId?: string) => {
    const cid = convId ?? conversationId
    if (!cid) return
    try {
      const result = await getConversationMessages(cid, 1, 1, 'DESC')
      const docs = result.data?.documents ?? []
      if (docs.length > 0) {
        const latestDoc = docs[0]
        const fileUrl = latestDoc.file_url.startsWith('/api')
          ? latestDoc.file_url
          : `/api${latestDoc.file_url}`
        const blob = (await api.get(fileUrl.replace('/api', ''), { responseType: 'blob' })) as Blob
        const newUrl = URL.createObjectURL(blob)
        if (pdfUrl) URL.revokeObjectURL(pdfUrl)
        setPdfUrl(newUrl)
      }
    } catch (e) { console.error(e) }
  }, [conversationId, pdfUrl])

  const loadConversationToState = useCallback((id: string, totalMsgs: number, resetPdf = true) => {
    const state = useResumeStore.getState(); setSupplementCount(0); setConversationId(id); setMessagesPage(1)
    setHasMoreHistory(totalMsgs > state.messages.length); if (resetPdf) setPdfUrl(state.fileBlobUrl); else if (state.fileBlobUrl) setPdfUrl(state.fileBlobUrl)
    loadReferenceFiles(id); loadDocHistory(id)
  }, [loadReferenceFiles, loadDocHistory])

  const removeReferenceFile = useCallback(async (id: number) => {
    if (id === 0) { setReferenceFiles((prev) => prev.filter((f) => f.id !== 0)); return }
    try { await deleteReferenceFile(conversationId, id); setReferenceFiles((prev) => prev.filter((f) => f.id !== id)); message.success('已删除') } catch (e) { message.error('删除失败') }
  }, [conversationId])

  const dequeue = useCallback(() => {
    loadReferenceFiles()
    setRequestQueue((prev) => {
      if (prev.length > 0) {
        const updated = prev.map((r, i) => (i === 0 ? { ...r, status: 'completed' as const } : r))
        const [, ...rest] = updated; setTimeout(() => processQueue(), 0); return rest
      }
      setTimeout(() => processQueue(), 0); return prev
    })
  }, [processQueue, loadReferenceFiles])

  const cancelRequest = useCallback((id: string) => {
    let key: string | undefined, wasSupp: boolean | undefined
    setRequestQueue((prev) => {
      const req = prev.find((r) => r.id === id)
      if (req) { key = req.disabledKey; wasSupp = req.wasSupplement }
      return prev.map((r) => r.id === id ? { ...r, canceled: true, status: 'failed' as const } : r)
    })
    if (key) { setDisabledOpts((prev) => { const n = new Set(prev); n.delete(key!); return n }); setDisabledMods((prev) => { const n = new Set(prev); n.delete(key!); return n }) }
    if (wasSupp) setSupplementCount((prev) => Math.max(0, prev - 1))
  }, [])

  const cancelAllPending = useCallback(() => {
    let keys: string[] = []; let drops = 0
    setRequestQueue((prev) => {
      keys = prev.filter((r) => r.status === 'pending').map((r) => r.disabledKey).filter(Boolean) as string[]
      drops = prev.filter((r) => r.status === 'pending' && r.wasSupplement).length
      return prev.map((r) => r.status === 'pending' ? { ...r, canceled: true, status: 'failed' as const } : r)
    })
    keys.forEach((k) => { setDisabledOpts((p) => { const n = new Set(p); n.delete(k); return n }); setDisabledMods((p) => { const n = new Set(p); n.delete(k); return n }) })
    if (drops) setSupplementCount((prev) => Math.max(0, prev - drops))
  }, [])

  const pendingQueueCount = useMemo(() => requestQueue.filter((r) => r.status === 'pending').length, [requestQueue])

  // ═══ 滚动 ═══
  const scrollToBottom = useCallback(() => chatPanelRef.current?.scrollToBottom(), [])

  const pushStatusMessages = useCallback((field: string) => {
    const ts = Date.now()
    setMessages((prev) => [...prev, { id: `temp-user-${ts}`, role: 'user', content: `确认修改：${field}` }, { id: `temp-status-${ts}`, role: 'assistant', content: `正在处理「${field}」...`, isProcessing: true }])
    const item = { field, timestamp: Date.now() }; pendingModsRef.current = [...pendingModsRef.current, item]; setPendingMods((prev) => [...prev, item])
    autoScroll.current = true; scrollToBottom()
  }, [scrollToBottom])

  const onChatSend = useCallback((text: string, files: File[]) => {
    if (!text.trim() && files.length === 0) return
    setFailedMessage(text)
    autoScroll.current = true; scrollToBottom()
    if (files.length > 0) {
      const optimisticDocs: ReferenceDoc[] = files.map((f) => ({ id: 0, original_name: f.name, file_type: f.name.split('.').pop()?.toLowerCase() || '', file_size: f.size, file_path: '', doc_type: 'reference', version: 0, created_at: Date.now(), ref_category: undefined }))
      setReferenceFiles((prev) => [...optimisticDocs, ...prev])
    }
    enqueueRequest({ type: 'search', execute: () => { setSupplementCount(0); chatRef.current?.sendMessage({ text }, { body: { type: 'search', conversationId, query: text, files: files.length > 0 ? files : undefined } }) } }, { text })
  }, [enqueueRequest, conversationId, scrollToBottom])

  const onApplyOptimization = useCallback((item: OptimizationItem, _idx: number, _msgIndex: number, _msg: Message) => {
    setDisabledOpts((prev) => new Set(prev).add(`${_msgIndex}-${_idx}`))
    enqueueRequest({ type: 'apply', disabledKey: `${_msgIndex}-${_idx}`, execute: () => {
      pushStatusMessages(item.field)
      try { chatRef.current?.sendMessage({ text: `采纳建议：${item.field}` }, { body: { type: 'apply', conversationId, displayText: `采纳优化建议：\n字段：${item.field}\n当前内容：${item.current}\n建议内容：${item.suggestion}`, optimization: { field: item.field, current: item.current, suggestion: item.suggestion, reason: item.reason || '' } } }) }
      catch (err) { console.error('Apply error:', err); message.error('采纳失败'); dequeue() }
    } }, { field: item.field })
  }, [enqueueRequest, conversationId, pushStatusMessages, dequeue])

  const acceptModification = useCallback((item: ModificationItem, _msgIndex: number, _modIdx: number) => {
    setSupplementCount(0)
    setDisabledMods((prev) => new Set(prev).add(`${_msgIndex}-${_modIdx}`))
    enqueueRequest({ type: 'accept', disabledKey: `${_msgIndex}-${_modIdx}`, execute: () => {
      pushStatusMessages(item.field)
      try { chatRef.current?.sendMessage({ text: `确认修改：${item.field}` }, { body: { type: 'accept', conversationId, optimization: { field: item.field, current: item.current, suggestion: item.suggestion, reason: item.reason || '' } } }) }
      catch (err) { console.error('Accept error:', err); message.error('确认修改失败'); dequeue() }
    } }, { field: item.field })
  }, [enqueueRequest, conversationId, pushStatusMessages, dequeue])

  const submitSupplement = useCallback((text: string) => {
    if (!text.trim()) return
    const query = currentSupplementField ? `之前要求修改「${currentSupplementField}」：${currentSupplementOriginal}\n现补充：${text}` : `补充修改要求：${text}`
    setSupplementCount((prev) => prev + 1)
    enqueueRequest({ type: 'search', wasSupplement: true, disabledKey: `${currentSupplementMsgIndex}-${currentSupplementModIdx}`, execute: () => { chatRef.current?.sendMessage({ text: `补充修改要求：${text}` }, { body: { type: 'search', conversationId, query, displayText: `补充修改要求：${text}` } }); chatPanelRef.current?.setInput?.('') } }, { text })
  }, [enqueueRequest, conversationId, currentSupplementField, currentSupplementOriginal, currentSupplementMsgIndex, currentSupplementModIdx])

  // ═══ 历史加载 ═══
  const loadMoreHistory = useCallback(async () => {
    if (historyLoading || !hasMoreHistory) return
    setHistoryLoading(true)
    try {
      const nextPage = messagesPage + 1
      const { getConversationMessages } = await import('@/api')
      const result = await getConversationMessages(conversationId, nextPage, MESSAGES_PAGE_SIZE, 'DESC')
      const data = result.data ?? result
      const apiMessages = (data.messages ?? []).reverse()
      if (apiMessages.length === 0 || messagesPage * MESSAGES_PAGE_SIZE >= (result.pagination?.total ?? 0)) { setHasMoreHistory(false) }
      else {
        const prevHeight = chatPanelRef.current?.getScrollHeight?.() ?? 0
        setMessages((prev) => [...apiMessages.map(mapApiMessage), ...prev])
        setMessagesPage(nextPage)
        setHasMoreHistory(nextPage * MESSAGES_PAGE_SIZE < (result.pagination?.total ?? 0))
        requestAnimationFrame(() => { const nh = chatPanelRef.current?.getScrollHeight?.() ?? 0; chatPanelRef.current?.restoreScrollPosition?.(nh - prevHeight) })
      }
    } catch (e) { console.error('Failed to load more history:', e); setMessagesPage((prev) => Math.max(1, prev - 1)) }
    finally { setHistoryLoading(false) }
  }, [historyLoading, hasMoreHistory, messagesPage, conversationId])

  const onChatScroll = useCallback((payload: { scrollTop: number; scrollHeight: number; clientHeight: number }) => {
    autoScroll.current = payload.scrollHeight - payload.scrollTop - payload.clientHeight < 80
    if (!autoScroll.current && hasMoreHistory && payload.scrollTop < 30) loadMoreHistory()
  }, [hasMoreHistory, loadMoreHistory])



  function autoTriggerSearch(query: string, id: string) { enqueueRequest({ type: 'search', execute: () => chatRef.current?.sendMessage({ text: query }, { body: { conversationId: id, query } }) }, { text: query }) }

  function triggerSearchIfNeeded() {
    const storeMsgs = resumeStore.messages
    if (storeMsgs.length > 0 && storeMsgs[storeMsgs.length - 1].role === 'user') {
      if (chatRef.current?.messages?.some((m: any) => m.role === 'assistant')) return
      autoTriggerSearch(storeMsgs[storeMsgs.length - 1].content, routeId!)
    }
  }

  // ═══ 初始加载 + 路由切换 ═══
  useEffect(() => {
    if (!routeId) { navigate('/editor', { replace: true }); return }
    sdkSyncedIds.current.clear(); setMessages([]); setPdfUrl(''); setDocVersions([]); setActiveVersionIdx(0); setError('')
    const init = async () => {
      try {
        setLoading(true)
        const { totalMessages } = await resumeStore.loadConversation(routeId)
        const state = useResumeStore.getState()
        const storeMsgs = state.messages
        setMessages(storeMsgs)
        loadConversationToState(routeId, totalMessages)
        const historyMessages = storeMsgs.map((m: any) => ({ id: String(m.id ?? ''), role: m.role, content: m.content, parts: m.parts ?? [{ type: 'text', text: m.content }] }))
        initChat(historyMessages)
        if (resumeStore.messages.length > 0) {
          setMessages((prev) => prev.map((m, i) => { const storeMsg = resumeStore.messages[i] as any; if (storeMsg?.reasoning) return { ...m, reasoning: storeMsg.reasoning }; return m }))
        }
        if (storeMsgs.length === 0 && state.initialPrompt) { autoTriggerSearch(state.initialPrompt, routeId) } else { triggerSearchIfNeeded() }
        scrollToBottom()
      } catch (e) { console.error(e); setError('加载会话失败') } finally { setLoading(false) }
    }
    init()
  }, [routeId])

  // ═══ 清理 ═══
  useEffect(() => { return () => { const state = useResumeStore.getState(); if (state.fileBlobUrl) URL.revokeObjectURL(state.fileBlobUrl); setPendingMods([]); sdkSyncedIds.current.clear() } }, [])

  if (loading) return <div className="flex justify-center items-center h-screen bg-[#f5f5f5]"><Skeleton active paragraph={{ rows: 8 }} style={{ width: '60%' }} /></div>
  if (error) return <div className="flex justify-center items-center h-screen bg-[#f5f5f5]"><Result status="error" title="加载失败" subTitle={error} extra={<Button type="primary" onClick={() => window.location.reload()}>重试</Button>} /></div>

  return (
    <div className="flex h-[calc(100vh-50px)]">
      <div className="flex-1 min-w-0 p-5 bg-[#f5f5f5] overflow-hidden">
        <PdfPreview pdfUrl={pdfUrl} loading={loading} error={error} onDownload={async () => { try { const blob = await renderResumePdf(resumeStore.resumeContent); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'resume.pdf'; a.click(); URL.revokeObjectURL(url) } catch (e) { message.error('下载失败') } }}
          versions={docVersions} activeIndex={activeVersionIdx}
          currentVersion={activeVersionIdx >= 0 && docVersions[activeVersionIdx] ? docVersions[activeVersionIdx].type === 'original' ? '原始简历' : `修改版本 v${docVersions[activeVersionIdx].version || ''}` : undefined}
          showRestore={docVersions.length > 1 && activeVersionIdx !== docVersions.length - 1}
          onSelectVersion={async (idx: number) => { if (idx === activeVersionIdx) return; const v = docVersions[idx]; if (!v) return; try { let blob: Blob; if (v.type === 'original' && resumeStore.resumeContent) blob = await renderResumePdf(resumeStore.resumeContent); else { const result = await api.get(`/rag/docs/${v.refId}/download`, { responseType: 'blob' }); blob = result as unknown as Blob } const url = URL.createObjectURL(blob); setPdfUrl((prev) => { if (prev && prev !== resumeStore.fileBlobUrl) URL.revokeObjectURL(prev); return url }); setActiveVersionIdx(idx) } catch (e) { message.error('加载版本失败') } }}
          onRestore={async () => { const v = docVersions[activeVersionIdx]; if (!v) return; try { const ts = Date.now(); setMessages((prev) => [...prev, { id: `local-restore-${ts}`, role: 'assistant', content: `已恢复到版本 v${v.version}` }]); autoScroll.current = true; scrollToBottom(); await restoreDocVersion(v.refId); message.success('已恢复'); loadDocHistory(); reloadPdfFromServer() } catch (e) { message.error('恢复失败') } }} />
      </div>
      <div className="w-[400px] shrink-0 p-5">
        <ChatPanel ref={chatPanelRef} messages={messages} isLoading={isStreaming} chatTitle={chatTitle} chatError={chatError}
          referenceFiles={referenceFiles} historyLoading={historyLoading} hasMoreHistory={hasMoreHistory} requestQueue={requestQueue as any}
          isProcessing={isProcessing} isSearchProcessing={isSearchProcessing} pendingCount={pendingQueueCount} disabledOpts={disabledOpts} disabledMods={disabledMods}
          onSend={onChatSend} onLoadMoreHistory={loadMoreHistory} onChatScroll={onChatScroll} onStop={handleStop}
          onRetrySend={() => { setChatError(''); const t = failedMessage; setFailedMessage(''); if (t) onChatSend(t, []) }}
          onCloseError={() => setChatError('')} onRemoveReferenceFile={removeReferenceFile}
          onApplyOptimization={onApplyOptimization} onAcceptModification={acceptModification} onSupplementModification={(item, msgIdx, modIdx) => { setCurrentSupplementField(item.field); setCurrentSupplementOriginal(item.current); setCurrentSupplementMsgIndex(msgIdx); setCurrentSupplementModIdx(modIdx); chatPanelRef.current?.openSupplementDialog() }}
          onRejectModification={(msgIdx, modIdx) => setDisabledMods((prev) => new Set(prev).add(`${msgIdx}-${modIdx}`))}
          onSubmitSupplement={submitSupplement} onToggleDrawer={() => setDrawerVisible(true)} onGoBack={() => navigate('/conversations')}
          onCancelRequest={cancelRequest} onCancelAllPending={cancelAllPending} onReorderQueue={(q: any[]) => setRequestQueue(q)}
          onToggleReasoning={(msgId: string) => { const cur = showReasoningMap.get(msgId) ?? false; showReasoningMap.set(msgId, !cur); setMessages((prev) => prev.map((m) => m.id === msgId ? { ...m, showReasoning: !cur } : m)) }} />
      </div>
      <ConversationDrawer visible={drawerVisible} onClose={() => setDrawerVisible(false)} />
    </div>
  )
}

// aiagentfe-vue/src/pages/EditorPage.vue
<template>
  <div class="editor-page">
    <div class="left-panel">
      <PdfPreview
        :pdf-url
        :loading
        :error
        :versions="docVersions"
        :active-index="activeVersionIdx"
        :current-version="currentVersionLabel"
        :show-restore="docVersions.length > 1 && activeVersionIdx !== docVersions.length - 1"
        @download="downloadPdf"
        @select-version="switchVersion"
        @restore="handleRestore"
      />
    </div>

    <div class="right-panel">
      <ChatPanel
        ref="chatPanelRef"
        :messages
        :is-loading
        :chat-title
        :chat-error
        :reference-files
        :history-loading
        :has-more-history
        :request-queue
        :is-processing
        :pending-count="pendingQueueCount"
        :disabled-opts
        :disabled-mods
        @send="onChatSend"
        @load-more-history="loadMoreHistory"
        @chat-scroll="onChatScroll"
        @retry-send="retrySend"
        @close-error="chatError = ''"
        @remove-reference-file="removeReferenceFile"
        @apply-optimization="onApplyOptimization"
        @accept-modification="
          (item, msgIndex, modIdx) => acceptModification(item, msgIndex, modIdx)
        "
        @supplement-modification="
          (item, msgIndex, modIdx) => supplementModification(item, msgIndex, modIdx)
        "
        @reject-modification="rejectModification"
        @submit-supplement="submitSupplement"
        @toggle-drawer="drawerVisible = true"
        @go-back="goBack"
        @cancel-request="cancelRequest"
        @cancel-all-pending="cancelAllPending"
        @reorder-queue="onReorderQueue"
        @toggle-reasoning="onToggleReasoning"
      />
    </div>

    <ConversationDrawer v-model:visible="drawerVisible" />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, nextTick, watch, computed } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { Chat } from '@ai-sdk/vue'
import type { UIMessage } from 'ai'
import { ElMessage } from 'element-plus'
import { useResumeStore } from '@/stores/resume'
import {
  getReferenceFiles,
  deleteReferenceFile,
  getDocHistory,
  restoreDocVersion,
  renderResumePdf,
  api,
  type ReferenceDoc,
  type DocVersion
} from '@/api'
import { MultipartChatTransport } from '@/lib/multipart-chat-transport'
import ConversationDrawer from '@/components/ConversationDrawer.vue'
import PdfPreview from '@/components/PdfPreview.vue'
import ChatPanel from '@/components/ChatPanel.vue'
import type { OptimizationItem, ModificationItem, Message } from '@/types/chat'

const router = useRouter()
const route = useRoute()
const resumeStore = useResumeStore()
const chatPanelRef = ref<InstanceType<typeof ChatPanel>>()
const pdfUrl = ref<string>('')
const conversationId = ref('')
const loading = ref(true)
const error = ref('')
const drawerVisible = ref(false)
const docVersions = ref<DocVersion[]>([])
const activeVersionIdx = ref(0)
const currentVersionLabel = computed(() => {
  const v = docVersions.value[activeVersionIdx.value]
  if (!v) return ''
  return v.type === 'original' ? '原始简历' : `修改版本 v${v.version}`
})

const messages = ref<Message[]>([])
const isLoading = ref(false)
const referenceFiles = ref<ReferenceDoc[]>([])
const historyLoading = ref(false)
const refFilesLoading = ref(false)
const messagesPage = ref(1)
const messagesTotal = ref(0)
const hasMoreHistory = ref(true)
const MESSAGES_PAGE_SIZE = 100

const chatTitle = computed(() => {
  return resumeStore.conversationTitle || '简历优化助手'
})

const pendingMods = ref<{ field: string; timestamp: number }[]>([])
const PENDING_MODS_TIMEOUT = 60000

function clearStalePendingMods() {
  const now = Date.now()
  pendingMods.value = pendingMods.value.filter((p) => now - p.timestamp < PENDING_MODS_TIMEOUT)
}

const chatError = ref('')
const failedMessage = ref('')
const supplementCount = ref(0)
const currentSupplementField = ref('')
const currentSupplementOriginal = ref('')
const currentSupplementMsgIndex = ref(-1)
const currentSupplementModIdx = ref(-1)

const MAX_SUPPLEMENTS = 3

const showReasoningMap = new Map<string, boolean>()
const autoScroll = ref(true)
let chat!: Chat<any>
let chatWatchHandle: (() => void) | null = null
const sdkSyncedIds = new Set<string>()

// 消息队列
interface QueuedRequest {
  id: string
  type: 'search' | 'apply' | 'accept'
  label: string
  execute: () => void
  canceled: boolean
  timestamp: number
  status: 'pending' | 'processing' | 'completed' | 'failed'
  disabledKey?: string
  wasSupplement?: boolean
}

const requestQueue = ref<QueuedRequest[]>([])
const isProcessing = ref(false)

function getLabel(type: string, payload?: any): string {
  if (type === 'search') return `发送消息：${payload?.text?.slice(0, 20) || '...'}`
  if (type === 'apply') return `采纳建议：${payload?.field || ''}`
  if (type === 'accept') return `确认修改：${payload?.field || ''}`
  return type
}

function enqueueRequest(
  req: Omit<QueuedRequest, 'id' | 'timestamp' | 'status' | 'label' | 'canceled'>,
  payload?: any
) {
  if (payload?.field) {
    const dupIdx = requestQueue.value.findIndex(
      (r) => r.status === 'pending' && r.type === req.type && r.label.includes(payload.field)
    )
    if (dupIdx !== -1) requestQueue.value.splice(dupIdx, 1)
  }
  requestQueue.value.push({
    ...req,
    id: `req_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
    label: getLabel(req.type, payload),
    status: 'pending',
    canceled: false,
    timestamp: Date.now()
  })
  if (!isProcessing.value) processQueue()
}

function processQueue() {
  while (requestQueue.value.length > 0 && requestQueue.value[0].canceled) {
    requestQueue.value.shift()
  }
  if (requestQueue.value.length === 0) {
    isProcessing.value = false
    return
  }
  isProcessing.value = true
  const current = requestQueue.value[0]
  current.status = 'processing'
  isLoading.value = true
  try {
    current.execute()
  } catch (err) {
    console.error('Queue execute error:', err)
    current.status = 'failed'
    requestQueue.value.shift()
    processQueue()
  }
}

function dequeue() {
  if (requestQueue.value.length > 0) {
    requestQueue.value[0].status = 'completed'
    requestQueue.value.shift()
  }
  // 每次队列完成一个请求后刷新参考资料列表，确保与服务端同步
  loadReferenceFiles()
  processQueue()
}

function cancelRequest(id: string) {
  const req = requestQueue.value.find((r) => r.id === id)
  if (req) {
    req.canceled = true
    req.status = 'failed'
    if (req.disabledKey) {
      const newOpts = new Set(disabledOpts.value)
      const newMods = new Set(disabledMods.value)
      newOpts.delete(req.disabledKey)
      newMods.delete(req.disabledKey)
      disabledOpts.value = newOpts
      disabledMods.value = newMods
    }
    if (req.wasSupplement && supplementCount.value > 0) {
      supplementCount.value--
    }
  }
}

function cancelAllPending() {
  requestQueue.value.forEach((r) => {
    if (r.status === 'pending') {
      r.canceled = true
      r.status = 'failed'
      if (r.disabledKey) {
        const newOpts = new Set(disabledOpts.value)
        const newMods = new Set(disabledMods.value)
        newOpts.delete(r.disabledKey)
        newMods.delete(r.disabledKey)
        disabledOpts.value = newOpts
        disabledMods.value = newMods
      }
      if (r.wasSupplement && supplementCount.value > 0) {
        supplementCount.value--
      }
    }
  })
}

function onReorderQueue(newQueue: QueuedRequest[]) {
  requestQueue.value = newQueue
}

const pendingQueueCount = computed(
  () => requestQueue.value.filter((r) => r.status === 'pending').length
)

// 禁用跟踪（已点击的建议/修改卡片）
const disabledOpts = ref<Set<string>>(new Set())
const disabledMods = ref<Set<string>>(new Set())

function markOptDisabled(msgIndex: number, idx: number) {
  disabledOpts.value = new Set(disabledOpts.value).add(`${msgIndex}-${idx}`)
}

function markModDisabled(msgIndex: number, modIdx: number) {
  disabledMods.value = new Set(disabledMods.value).add(`${msgIndex}-${modIdx}`)
}

function extractMessageContent(sdkMsg: UIMessage): string {
  const textParts = sdkMsg.parts?.filter((p: any) => p.type === 'text')
  return (
    textParts
      ?.map((p: any) => p.text ?? p.content ?? '')
      .filter(Boolean)
      .join('\n') ?? ''
  )
}

function extractReasoning(sdkMsg: UIMessage): string {
  const reasoningParts = sdkMsg.parts?.filter((p: any) => p.type === 'reasoning')
  return (
    reasoningParts
      ?.map((p: any) => p.text ?? p.reasoning ?? '')
      .filter(Boolean)
      .join('\n') || ''
  )
}

function extractModifications(sdkMsg: UIMessage): ModificationItem[] {
  const modList: ModificationItem[] = []
  const toolParts = (sdkMsg.parts?.filter(
    (p: any) =>
      p.type === 'dynamic-tool' || p.type === 'tool-invocation' || p.type?.startsWith('tool-')
  ) ?? []) as any[]
  for (const part of toolParts) {
    const output = part.output ?? part.toolInvocation?.result ?? part.toolInvocation?.output
    if (output?.modification) {
      modList.push(output.modification)
    }
  }
  return modList
}

function extractOptimizations(sdkMsg: UIMessage): OptimizationItem[] {
  const optList: OptimizationItem[] = []
  const toolParts = (sdkMsg.parts?.filter(
    (p: any) =>
      p.type === 'dynamic-tool' || p.type === 'tool-invocation' || p.type?.startsWith('tool-')
  ) ?? []) as any[]
  for (const part of toolParts) {
    const output = part.output ?? part.toolInvocation?.result ?? part.toolInvocation?.output
    if (output?.optimization) {
      optList.push(output.optimization)
    }
    if (output?.optimizations) {
      optList.push(...output.optimizations)
    }
  }
  return optList
}

function mapSdkMessages(sdkMessages: UIMessage[]): Message[] {
  return sdkMessages.map((msg) => {
    const content = extractMessageContent(msg)
    return {
      id: msg.id ?? '',
      role: msg.role as 'user' | 'assistant',
      content,
      reasoning: extractReasoning(msg),
      showReasoning: showReasoningMap.get(msg.id ?? '') ?? false,
      optimizations: extractOptimizations(msg),
      modifications: extractModifications(msg)
    }
  })
}

function mapApiMessage(m: { role: string; content: string; reasoning?: string }): Message {
  return {
    id: '',
    role: m.role as 'user' | 'assistant',
    content: m.content,
    reasoning: m.reasoning || '',
    showReasoning: false,
    optimizations: []
  }
}

const fetchWithAuth: typeof fetch = async (input, init) => {
  const headers = new Headers(init?.headers)
  const token = localStorage.getItem('auth_token')
  const phone = localStorage.getItem('login_phone')
  if (token) headers.set('Authorization', `Bearer ${token}`)
  if (phone) headers.set('X-Phone', phone)
  return fetch(input, { ...init, headers })
}

async function loadReferenceFiles() {
  if (!conversationId.value) return
  refFilesLoading.value = true
  try {
    const result = await getReferenceFiles(conversationId.value)
    referenceFiles.value = result.docs || []
  } catch (e) {
    console.error('Failed to load reference files:', e)
  } finally {
    refFilesLoading.value = false
  }
}

async function loadDocHistory() {
  if (!conversationId.value) return
  try {
    const result = await getDocHistory(conversationId.value)
    docVersions.value = result.versions || []
    activeVersionIdx.value = docVersions.value.length - 1 // 默认最新
  } catch (e) {
    console.error('Failed to load doc history:', e)
  }
}

async function switchVersion(idx: number) {
  if (idx === activeVersionIdx.value) return
  const v = docVersions.value[idx]
  if (!v) return
  let blob: Blob
  if (v.type === 'original' && resumeStore.resumeContent) {
    blob = await renderResumePdf(resumeStore.resumeContent)
  } else {
    blob = (await api.get(`/rag/docs/${v.refId}/download`, { responseType: 'blob' })) as Blob
  }
  const newUrl = URL.createObjectURL(blob)
  if (pdfUrl.value) URL.revokeObjectURL(pdfUrl.value)
  pdfUrl.value = newUrl
  activeVersionIdx.value = idx
}

async function handleRestore(refId: number) {
  try {
    await restoreDocVersion(refId)
    ElMessage.success('已恢复到该版本')
    await loadDocHistory()
    if (conversationId.value) {
      const { getConversationMessages } = await import('@/api')
      const result = await getConversationMessages(conversationId.value, 1, 1, 'DESC')
      const docs = result.data?.documents ?? []
      if (docs.length > 0) {
        const latestDoc = docs[0]
        const fileUrl = latestDoc.file_url.startsWith('/api')
          ? latestDoc.file_url
          : `/api${latestDoc.file_url}`
        const blob = (await api.get(fileUrl.replace('/api', ''), { responseType: 'blob' })) as Blob
        if (pdfUrl.value) URL.revokeObjectURL(pdfUrl.value)
        pdfUrl.value = URL.createObjectURL(blob)
      }
    }
  } catch (e) {
    console.error('Failed to restore version:', e)
    ElMessage.error('恢复失败')
  }
}

function onChatScroll(payload: { scrollTop: number; scrollHeight: number; clientHeight: number }) {
  const isNearBottom = payload.scrollHeight - payload.scrollTop - payload.clientHeight < 80
  autoScroll.value = isNearBottom
  if (!isNearBottom && hasMoreHistory.value && payload.scrollTop < 30) {
    loadMoreHistory()
  }
}

function onChatSend(text: string, files: File[]) {
  if (!text.trim() && files.length === 0) return
  failedMessage.value = text
  autoScroll.value = true
  isLoading.value = true

  // 乐观更新：文件发出后立即插入临时项，dequeue 时会刷新真实数据
  if (files.length > 0) {
    const optimisticDocs = files.map((f) => ({
      id: 0,
      original_name: f.name,
      file_type: f.name.split('.').pop()?.toLowerCase() || '',
      file_size: f.size,
      file_path: '',
      doc_type: 'reference' as const,
      version: 0,
      created_at: Date.now(),
      ref_category: undefined
    }))
    referenceFiles.value = [...optimisticDocs, ...referenceFiles.value]
  }

  enqueueRequest(
    {
      type: 'search',
      execute: () => {
        supplementCount.value = 0
        chat.sendMessage(
          { text },
          {
            body: {
              type: 'search',
              conversationId: conversationId.value,
              query: text,
              files: files.length > 0 ? files : undefined
            }
          }
        )
      }
    },
    { text }
  )

  chatPanelRef.value?.scrollToBottom()
}

async function removeReferenceFile(refId: number) {
  if (!conversationId.value) return
  try {
    await deleteReferenceFile(conversationId.value, refId)
    referenceFiles.value = referenceFiles.value.filter((d) => d.id !== refId)
    ElMessage.success('参考资料已删除')
  } catch {
    ElMessage.error('删除失败')
  }
}

function retrySend() {
  chatError.value = ''
  const text = failedMessage.value
  failedMessage.value = ''
  if (text) {
    onChatSend(text, [])
  }
}

async function reloadPdfFromServer() {
  if (!conversationId.value) return
  console.log('[PDF] reloadPdfFromServer called for:', conversationId.value)
  console.log('[PDF] caller stack:', new Error().stack?.split('\n').slice(2, 5).join(' → '))
  try {
    const { getConversationMessages } = await import('@/api')
    const result = await getConversationMessages(conversationId.value, 1, 1, 'DESC')
    const docs = result.data?.documents ?? []
    console.log('[PDF] docs count:', docs.length, 'file_url:', docs[0]?.file_url)
    if (docs.length > 0) {
      const latestDoc = docs[0]
      const fileUrl = latestDoc.file_url.startsWith('/api')
        ? latestDoc.file_url
        : `/api${latestDoc.file_url}`
      console.log('[PDF] fetching:', fileUrl)
      const blob = (await api.get(fileUrl.replace('/api', ''), {
        responseType: 'blob'
      })) as Blob
      const newUrl = URL.createObjectURL(blob)
      if (pdfUrl.value) URL.revokeObjectURL(pdfUrl.value)
      pdfUrl.value = newUrl
      console.log('[PDF] updated blob URL:', pdfUrl.value.slice(0, 30))
    }
  } catch (e) {
    console.error('Failed to reload PDF from server:', e)
  }
}

function downloadPdf() {
  if (!pdfUrl.value) {
    ElMessage.warning('PDF 尚未生成')
    return
  }
  const a = document.createElement('a')
  a.href = pdfUrl.value
  a.download = 'resume.pdf'
  a.click()
}

function goBack() {
  router.push('/conversations')
}

function loadConversationToState(id: string, totalMsgs: number, resetPdf = true) {
  supplementCount.value = 0
  conversationId.value = id
  messagesPage.value = 1
  messagesTotal.value = totalMsgs
  hasMoreHistory.value = totalMsgs > messages.value.length
  if (resetPdf) {
    pdfUrl.value = resumeStore.fileBlobUrl
  } else if (resumeStore.fileBlobUrl) {
    pdfUrl.value = resumeStore.fileBlobUrl
  }
  activeVersionIdx.value = 0
  docVersions.value = []
  loadReferenceFiles()
  loadDocHistory()
}

function autoTriggerSearch(query: string, id: string) {
  isLoading.value = true
  enqueueRequest(
    {
      type: 'search',
      execute: () => {
        chat.sendMessage({ text: query }, { body: { conversationId: id, query } })
      }
    },
    { text: query }
  )
}

function triggerSearchIfNeeded() {
  const msgs = resumeStore.messages
  if (msgs.length > 0 && msgs[msgs.length - 1].role === 'user') {
    const sdkMsgs = chat.messages ?? []
    const hasAssistantReply = sdkMsgs.some((m) => m.role === 'assistant')
    if (hasAssistantReply) return
    autoTriggerSearch(msgs[msgs.length - 1].content, conversationId.value)
  }
}

async function loadMoreHistory() {
  if (!hasMoreHistory.value || historyLoading.value || !conversationId.value) return
  historyLoading.value = true
  const prevScrollHeight = chatPanelRef.value?.getScrollHeight() ?? 0

  try {
    messagesPage.value++
    const { getConversationMessages } = await import('@/api')
    const result = await getConversationMessages(
      conversationId.value,
      messagesPage.value,
      MESSAGES_PAGE_SIZE,
      'DESC'
    )
    const apiMessages = (result.data?.messages ?? []).reverse()
    if (apiMessages.length === 0) {
      hasMoreHistory.value = false
      return
    }

    const loadedCount = result.pagination?.total ?? messagesTotal.value
    messagesTotal.value = loadedCount
    hasMoreHistory.value = messages.value.length + apiMessages.length < loadedCount

    messages.value = [...apiMessages.map(mapApiMessage), ...messages.value]

    await nextTick()
    chatPanelRef.value?.restoreScrollPosition(prevScrollHeight)
  } catch (e) {
    console.error('Failed to load more history:', e)
    messagesPage.value--
  } finally {
    historyLoading.value = false
  }
}

function initChat(historyMessages?: any[]) {
  if (chatWatchHandle) {
    chatWatchHandle()
    chatWatchHandle = null
  }

  const transport = new MultipartChatTransport({
    fetch: fetchWithAuth
  })

  chat = new Chat({
    transport,
    messages: historyMessages,
    onError: (err: Error) => {
      if (err.message?.includes('reasoning-delta for missing reasoning part')) {
        isLoading.value = false
        dequeue()
        return
      }
      pendingMods.value.splice(0)
      console.error('Chat error:', err)
      chatError.value = err.message || '操作失败'
      failedMessage.value = ''
      isLoading.value = false
      dequeue()
    },
    onFinish: async ({ messages: sdkMessages }) => {
      isLoading.value = false

      sdkMessages.forEach((msg) => {
        if (msg.id && !showReasoningMap.has(msg.id)) showReasoningMap.set(msg.id, false)
      })

      if (pendingMods.value.length > 0) {
        const pending = pendingMods.value[0]
        pendingMods.value.splice(0)

        function clearManualAndEmpty() {
          messages.value = messages.value.filter((m) => {
            if (m.id?.startsWith('temp-')) return false
            if (
              m.role === 'assistant' &&
              !m.content &&
              !m.optimizations?.length &&
              !m.modifications?.length
            )
              return false
            return true
          })
        }

        clearManualAndEmpty()

        messages.value.push(
          { id: `result-user-${Date.now()}`, role: 'user', content: `确认修改：${pending.field}` },
          {
            id: `result-status-${Date.now()}`,
            role: 'assistant',
            content: `正在处理「${pending.field}」...`
          },
          {
            id: `result-done-${Date.now()}`,
            role: 'assistant',
            content: '已采纳建议并生成修改内容'
          }
        )

        // 标记本次 accept 的 SDK 消息为已同步，防止 watch 重复推送
        sdkMessages.forEach((m) => {
          if (m.id) sdkSyncedIds.add(m.id)
        })

        if (conversationId.value) {
          reloadPdfFromServer()
          loadDocHistory()
        }
      }

      const newStoreMessages = sdkMessages.map((m) => {
        const existing = resumeStore.messages.find((sm) => sm.id === m.id)
        return {
          id: m.id ?? '',
          role: m.role as 'user' | 'assistant',
          content: extractMessageContent(m),
          reasoning: existing?.reasoning || extractReasoning(m) || '',
          optimizations: existing?.optimizations || extractOptimizations(m) || [],
          modifications: existing?.modifications || extractModifications(m) || []
        }
      })
      resumeStore.messages = newStoreMessages

      chatPanelRef.value?.scrollToBottom()
      dequeue()
    }
  })

  const initialMsgs = chat.messages ?? []
  initialMsgs.forEach((m) => {
    if (m.id) sdkSyncedIds.add(m.id)
  })

  chatWatchHandle = watch(
    () => chat.messages,
    (sdkMessages) => {
      if (!sdkMessages || sdkMessages.length === 0) return
      if (pendingMods.value.length > 0) return

      clearStalePendingMods()
      if (pendingMods.value.length > 0) return

      const newSdkMessages = sdkMessages.filter((m) => m.id && !sdkSyncedIds.has(m.id))
      if (newSdkMessages.length > 0) {
        const newLocalMessages = mapSdkMessages(newSdkMessages)
        messages.value.push(...newLocalMessages)
        newSdkMessages.forEach((m) => {
          if (m.id) sdkSyncedIds.add(m.id)
        })
      }

      const lastSdk = sdkMessages[sdkMessages.length - 1]
      if (lastSdk?.id) {
        const localIdx = messages.value.findIndex((m) => m.id === lastSdk.id)
        if (localIdx !== -1) {
          const newContent = extractMessageContent(lastSdk)
          if (newContent) {
            messages.value[localIdx].content = newContent
            messages.value[localIdx].optimizations = extractOptimizations(lastSdk)
          }
          messages.value[localIdx].reasoning = extractReasoning(lastSdk)
          messages.value[localIdx].modifications = extractModifications(lastSdk)
        }
      }

      if (autoScroll.value) {
        chatPanelRef.value?.scrollToBottom()
      }
    },
    { deep: true }
  )

  messages.value = mapSdkMessages(chat.messages ?? [])

  // 合并 store 中的 reasoning（历史消息的 parts 不含 reasoning）
  if (resumeStore.messages.length > 0) {
    resumeStore.messages.forEach((storeMsg, i) => {
      if ((storeMsg as any).reasoning && messages.value[i]) {
        messages.value[i].reasoning = (storeMsg as any).reasoning
      }
    })
  }
}

function pushStatusMessages(field: string) {
  const ts = Date.now()
  messages.value.push({
    id: `temp-user-${ts}`,
    role: 'user',
    content: `确认修改：${field}`
  })
  messages.value.push({
    id: `temp-status-${ts}`,
    role: 'assistant',
    content: `正在处理「${field}」...`,
    isProcessing: true
  })
  pendingMods.value.push({ field, timestamp: Date.now() })
  autoScroll.value = true
  chatPanelRef.value?.scrollToBottom()
}

async function onApplyOptimization(
  item: OptimizationItem,
  idx: number,
  msgIndex: number,
  _msg: Message
) {
  markOptDisabled(msgIndex, idx)

  enqueueRequest(
    {
      type: 'apply',
      disabledKey: `${msgIndex}-${idx}`,
      execute: () => {
        pushStatusMessages(item.field)
        try {
          chat.sendMessage(
            {
              text: `采纳优化建议：\n字段：${item.field}\n当前内容：${item.current}\n建议内容：${item.suggestion}`
            },
            { body: { type: 'apply', conversationId: conversationId.value, optimization: item } }
          )
        } catch (err) {
          console.error('采纳失败:', err)
          ElMessage.error('采纳失败')
          isLoading.value = false
          dequeue()
        }
      }
    },
    { field: item.field }
  )
}

async function acceptModification(item: ModificationItem, msgIndex: number, modIdx: number) {
  supplementCount.value = 0
  markModDisabled(msgIndex, modIdx)
  enqueueRequest(
    {
      type: 'accept',
      disabledKey: `${msgIndex}-${modIdx}`,
      execute: () => {
        pushStatusMessages(item.field)
        try {
          chat.sendMessage(
            { text: `确认修改：${item.field}` },
            {
              body: {
                type: 'accept',
                conversationId: conversationId.value,
                optimization: {
                  field: item.field,
                  current: item.current,
                  suggestion: item.suggestion,
                  reason: item.reason || '',
                }
              }
            }
          )
        } catch (err) {
          console.error('确认修改失败:', err)
          ElMessage.error('确认修改失败')
          isLoading.value = false
          dequeue()
        }
      }
    },
    { field: item.field }
  )
}

function supplementModification(item: ModificationItem, msgIndex: number, modIdx: number) {
  if (supplementCount.value >= MAX_SUPPLEMENTS) {
    ElMessage.warning(`最多补充${MAX_SUPPLEMENTS}次`)
    return
  }
  markModDisabled(msgIndex, modIdx)
  currentSupplementField.value = item.field
  currentSupplementOriginal.value = item.suggestion
  currentSupplementMsgIndex.value = msgIndex
  currentSupplementModIdx.value = modIdx
  chatPanelRef.value?.openSupplementDialog()
}

async function submitSupplement(text: string) {
  const context = currentSupplementField.value
    ? `之前要求修改「${currentSupplementField.value}」：${currentSupplementOriginal.value}\n现补充：${text}`
    : `补充修改要求：${text}`
  supplementCount.value++
  chatPanelRef.value?.setInput('')
  isLoading.value = true
  enqueueRequest(
    {
      type: 'search',
      wasSupplement: true,
      disabledKey: `${currentSupplementMsgIndex.value}-${currentSupplementModIdx.value}`,
      execute: () => {
        chat.sendMessage(
          { text: `补充修改要求：${text}` },
          {
            body: {
              conversationId: conversationId.value,
              query: context,
              displayText: `补充修改要求：${text}`
            }
          }
        )
      }
    },
    { text: context }
  )
}

function onToggleReasoning(msgId: string) {
  const current = showReasoningMap.get(msgId) ?? false
  showReasoningMap.set(msgId, !current)
  const msg = messages.value.find((m) => m.id === msgId)
  if (msg) msg.showReasoning = !current
}

function rejectModification(msgIndex: number, modIdx: number) {
  supplementCount.value = 0
  markModDisabled(msgIndex, modIdx)
}

onUnmounted(() => {
  if (pdfUrl.value && pdfUrl.value !== resumeStore.fileBlobUrl) {
    URL.revokeObjectURL(pdfUrl.value)
  }
  pdfUrl.value = ''
  pendingMods.value = []
  sdkSyncedIds.clear()
})

onMounted(async () => {
  const routeId = route.params.id as string
  if (!routeId) {
    router.push('/conversations')
    return
  }

  try {
    const { totalMessages, initialPrompt: loadedInitialPrompt } =
      await resumeStore.loadConversation(routeId)
    conversationId.value = routeId
    loadConversationToState(routeId, totalMessages)

    const historyMessages = resumeStore.messages.map((m) => ({
      id: `msg-${crypto.randomUUID()}`,
      role: m.role,
      parts: [{ type: 'text', text: m.content }]
    }))

    initChat(historyMessages)

    if (resumeStore.fileBlobUrl) {
      pdfUrl.value = resumeStore.fileBlobUrl
    }

    if (resumeStore.messages.length === 0 && loadedInitialPrompt) {
      autoTriggerSearch(loadedInitialPrompt, routeId)
    } else {
      triggerSearchIfNeeded()
    }

    loading.value = false

    await nextTick()
    chatPanelRef.value?.scrollToBottom()
  } catch (e) {
    console.error('Failed to load conversation:', e)
    error.value = '加载会话失败'
    loading.value = false
  }
})

watch(
  () => route.params.id,
  async (newId) => {
    if (newId && newId !== conversationId.value) {
      loading.value = true
      messages.value = []
      showReasoningMap.clear()
      try {
        const { totalMessages, initialPrompt: newInitialPrompt } =
          await resumeStore.loadConversation(newId as string)
        conversationId.value = newId as string
        loadConversationToState(newId as string, totalMessages, false)

        const historyMessages = resumeStore.messages.map((m) => ({
          id: `msg-${crypto.randomUUID()}`,
          role: m.role as 'user' | 'assistant',
          parts: [{ type: 'text', text: m.content }]
        }))

        initChat(historyMessages)

        if (resumeStore.fileBlobUrl) {
          pdfUrl.value = resumeStore.fileBlobUrl
        }

        if (resumeStore.messages.length === 0 && newInitialPrompt) {
          autoTriggerSearch(newInitialPrompt, newId as string)
        } else {
          triggerSearchIfNeeded()
        }

        loading.value = false

        await nextTick()
        chatPanelRef.value?.scrollToBottom()
      } catch {
        error.value = '切换会话失败'
        loading.value = false
      }
    }
  }
)
</script>

<style scoped>
.editor-page {
  display: flex;
  height: calc(100vh - 50px);
}

.left-panel {
  flex: 1;
  padding: 20px;
  background: #f5f5f5;
  overflow: hidden;
}

.right-panel {
  width: 400px;
  padding: 20px;
  background: white;
}
</style>
