// aiagentfe-vue/src/pages/DocumentLibraryPage.vue
<template>
  <div class="doc-library-page">
    <div class="page-container">
      <div class="page-header">
        <h2>我的知识库</h2>
        <el-button type="primary" @click="showUpload = true">
          <el-icon><Plus /></el-icon>
          上传文档
        </el-button>
      </div>

      <div v-if="showUpload" class="upload-section">
        <el-card>
          <template #header>
            <div class="upload-header">
              <span>上传文档到知识库</span>
              <el-button size="small" @click="showUpload = false"> 取消 </el-button>
            </div>
          </template>

          <div
            class="upload-area"
            @click="triggerFile"
            @dragover.prevent
            @drop.prevent="handleDrop"
          >
            <input
              ref="fileInputRef"
              type="file"
              accept=".pdf,.txt"
              style="display: none"
              @change="handleFileSelect"
            />
            <div v-if="!selectedFile" class="upload-placeholder">
              <el-icon :size="48">
                <UploadFilled />
              </el-icon>
              <p>点击或拖拽上传 PDF / TXT 文件</p>
            </div>
            <div v-else class="file-info">
              <el-icon :size="32">
                <Document />
              </el-icon>
              <span>{{ selectedFile.name }}</span>
              <el-button size="small" @click.stop="clearFile"> 重新选择 </el-button>
            </div>
          </div>

          <el-form class="upload-form" label-width="80px">
            <el-form-item label="文档类型">
              <el-radio-group v-model="docType">
                <el-radio value="reference_doc"> 参考资料 </el-radio>
                <el-radio value="excellent_resume"> 优秀简历 </el-radio>
              </el-radio-group>
            </el-form-item>
            <el-form-item label="分类">
              <el-input v-model="category" placeholder="可选，如：前端开发、产品经理" />
            </el-form-item>
            <el-form-item>
              <el-button
                type="primary"
                :disabled="!selectedFile || uploading"
                :loading="uploading"
                @click="handleUpload"
              >
                {{ uploading ? '上传中...' : '上传并索引' }}
              </el-button>
            </el-form-item>
          </el-form>
        </el-card>
      </div>

      <div v-if="loading" class="loading-wrap">
        <el-icon class="is-loading" :size="32">
          <Loading />
        </el-icon>
        <p>加载中...</p>
      </div>

      <el-empty v-else-if="documents.length === 0" description="知识库为空，点击上方按钮上传文档" />

      <div v-else class="doc-list">
        <el-card v-for="doc in documents" :key="doc.id" class="doc-card">
          <div class="doc-card-content">
            <div class="doc-title">
              <el-icon><Document /></el-icon>
              {{ doc.original_name }}
            </div>
            <div class="doc-meta">
              <el-tag size="small" :type="doc.doc_type === 'excellent_resume' ? 'success' : 'info'">
                {{ doc.doc_type === 'excellent_resume' ? '优秀简历' : '参考资料' }}
              </el-tag>
              <span v-if="doc.category" class="doc-category">{{ doc.category }}</span>
              <span class="doc-size">{{ formatSize(doc.file_size) }}</span>
              <span class="doc-time">{{ formatTime(doc.created_at) }}</span>
            </div>
          </div>
          <div class="doc-actions">
            <el-switch
              :model-value="doc.active === 1"
              size="small"
              @change="(val: boolean) => handleToggle(doc.id, val)"
            />
            <el-button type="danger" :icon="Delete" link @click="handleDelete(doc.id)">
              删除
            </el-button>
          </div>
        </el-card>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus, UploadFilled, Document, Loading, Delete } from '@element-plus/icons-vue'
import {
  getUserDocuments,
  uploadUserDocument,
  deleteUserDocument,
  toggleUserDocument,
  type UserDocument
} from '@/api'
import { formatTime } from '@/lib/format'

const showUpload = ref(false)
const uploading = ref(false)
const loading = ref(false)
const selectedFile = ref<File | null>(null)
const docType = ref('reference_doc')
const category = ref('')
const fileInputRef = ref<HTMLInputElement>()
const documents = ref<UserDocument[]>([])

async function fetchDocuments() {
  loading.value = true
  try {
    const result = await getUserDocuments()
    documents.value = result.data
  } catch (e) {
    console.error('Failed to fetch documents:', e)
    ElMessage.error('加载文档列表失败')
  } finally {
    loading.value = false
  }
}

onMounted(fetchDocuments)

function triggerFile() {
  fileInputRef.value?.click()
}

function handleFileSelect(e: Event) {
  const target = e.target as HTMLInputElement
  const file = target.files?.[0]
  if (file) selectedFile.value = file
}

function handleDrop(e: DragEvent) {
  const file = e.dataTransfer?.files[0]
  if (file && (file.type === 'application/pdf' || file.name.endsWith('.txt'))) {
    selectedFile.value = file
  } else {
    ElMessage.warning('请上传 PDF 或 TXT 文件')
  }
}

function clearFile() {
  selectedFile.value = null
  if (fileInputRef.value) fileInputRef.value.value = ''
}

async function handleUpload() {
  if (!selectedFile.value) return
  uploading.value = true
  try {
    await uploadUserDocument(selectedFile.value, docType.value, category.value || undefined)
    ElMessage.success('文档上传成功，已开始索引')
    showUpload.value = false
    clearFile()
    docType.value = 'reference_doc'
    category.value = ''
    await fetchDocuments()
  } catch (e: any) {
    console.error('Upload failed:', e)
    ElMessage.error(e?.response?.data?.error || '上传失败，请重试')
  } finally {
    uploading.value = false
  }
}

async function handleToggle(id: number, active: boolean) {
  try {
    await toggleUserDocument(id, active ? 1 : 0)
    const doc = documents.value.find((d) => d.id === id)
    if (doc) doc.active = active ? 1 : 0
    ElMessage.success(active ? '已启用' : '已禁用')
  } catch (e) {
    console.error('Toggle failed:', e)
    ElMessage.error('操作失败')
  }
}

async function handleDelete(id: number) {
  try {
    await ElMessageBox.confirm('确定要删除这个文档吗？', '确认删除', {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      type: 'warning'
    })
    await deleteUserDocument(id)
    documents.value = documents.value.filter((d) => d.id !== id)
    ElMessage.success('已删除')
  } catch (e) {
    if (e !== 'cancel') {
      console.error('Delete failed:', e)
      ElMessage.error('删除失败')
    }
  }
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return bytes + ' B'
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB'
  return (bytes / 1024 / 1024).toFixed(1) + ' MB'
}
</script>

<style scoped>
.doc-library-page {
  padding-top: 50px;
  min-height: 100vh;
  background: #f5f7fa;
}

.page-container {
  max-width: 800px;
  margin: 0 auto;
  padding: 24px 16px;
}

.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
}

.page-header h2 {
  margin: 0;
  font-size: 20px;
  color: #333;
}

.upload-section {
  margin-bottom: 24px;
}

.upload-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-weight: 600;
}

.upload-area {
  border: 2px dashed #dcdfe6;
  border-radius: 8px;
  padding: 40px 20px;
  text-align: center;
  cursor: pointer;
  transition: border-color 0.2s;
  margin-bottom: 16px;
}

.upload-area:hover {
  border-color: #409eff;
}

.upload-placeholder {
  color: #909399;
}

.upload-placeholder p {
  margin-top: 8px;
  font-size: 14px;
}

.file-info {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 12px;
  color: #333;
}

.upload-form {
  margin-top: 16px;
}

.loading-wrap {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 60px 0;
  color: #909399;
  gap: 12px;
}

.doc-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.doc-card {
  transition: box-shadow 0.2s;
}

.doc-card:hover {
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.1);
}

.doc-card-content {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.doc-title {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 15px;
  font-weight: 500;
  color: #333;
}

.doc-meta {
  display: flex;
  align-items: center;
  gap: 12px;
  font-size: 12px;
  color: #999;
}

.doc-category {
  padding: 2px 8px;
  background: #f0f2f5;
  border-radius: 4px;
}

.doc-actions {
  display: flex;
  align-items: center;
  gap: 16px;
  margin-top: 12px;
  padding-top: 12px;
  border-top: 1px solid #f0f0f0;
}
</style>

// aiagentfe-react/src/pages/DocumentLibraryPage.tsx
import React, { useState, useEffect, useRef } from 'react'
import { Card, Button, Radio, Input, Switch, message, Modal, Tag, Empty, Spin } from 'antd'
import { PlusOutlined, UploadOutlined, FileTextOutlined, DeleteOutlined } from '@ant-design/icons'
import {
  getUserDocuments,
  uploadUserDocument,
  deleteUserDocument,
  toggleUserDocument,
  type UserDocument
} from '@/api'
import { formatTime } from '@/lib/format'

function formatSize(bytes: number): string {
  if (bytes < 1024) return bytes + ' B'
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB'
  return (bytes / 1024 / 1024).toFixed(1) + ' MB'
}

export default function DocumentLibraryPage() {
  const [showUpload, setShowUpload] = useState(false)
  const [uploading, setUploading] = useState(false)
  const [loading, setLoading] = useState(false)
  const [selectedFile, setSelectedFile] = useState<File | null>(null)
  const [docType, setDocType] = useState('reference_doc')
  const [category, setCategory] = useState('')
  const [documents, setDocuments] = useState<UserDocument[]>([])
  const fileInputRef = useRef<HTMLInputElement>(null)

  const fetchDocuments = async () => {
    setLoading(true)
    try {
      const result = await getUserDocuments()
      setDocuments(result.data)
    } catch (e) {
      console.error('Failed to fetch documents:', e)
      message.error('加载文档列表失败')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    fetchDocuments()
  }, [])

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (file) setSelectedFile(file)
  }

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault()
    const file = e.dataTransfer?.files[0]
    if (file && (file.type === 'application/pdf' || file.name.endsWith('.txt'))) {
      setSelectedFile(file)
    } else {
      message.warning('请上传 PDF 或 TXT 文件')
    }
  }

  const clearFile = () => {
    setSelectedFile(null)
    if (fileInputRef.current) fileInputRef.current.value = ''
  }

  const handleUpload = async () => {
    if (!selectedFile) return
    setUploading(true)
    try {
      await uploadUserDocument(selectedFile, docType, category || undefined)
      message.success('文档上传成功，已开始索引')
      setShowUpload(false)
      clearFile()
      setDocType('reference_doc')
      setCategory('')
      await fetchDocuments()
    } catch (e: any) {
      console.error('Upload failed:', e)
      message.error(e?.response?.data?.error || '上传失败，请重试')
    } finally {
      setUploading(false)
    }
  }

  const handleToggle = async (id: number, active: boolean) => {
    try {
      await toggleUserDocument(id, active ? 1 : 0)
      setDocuments((prev) => prev.map((d) => (d.id === id ? { ...d, active: active ? 1 : 0 } : d)))
      message.success(active ? '已启用' : '已禁用')
    } catch (e) {
      console.error('Toggle failed:', e)
      message.error('操作失败')
    }
  }

  const handleDelete = (id: number) => {
    Modal.confirm({
      title: '确认删除',
      content: '确定要删除这个文档吗？',
      okText: '确定',
      cancelText: '取消',
      onOk: async () => {
        try {
          await deleteUserDocument(id)
          setDocuments((prev) => prev.filter((d) => d.id !== id))
          message.success('已删除')
        } catch (e) {
          console.error('Delete failed:', e)
          message.error('删除失败')
        }
      }
    })
  }

  return (
    <div className="min-h-screen bg-[#f5f7fa]">
      <div className="max-w-[800px] mx-auto py-6 px-4">
        <div className="flex justify-between items-center mb-5">
          <h2 className="m-0 text-xl text-[#333]">我的知识库</h2>
          <Button type="primary" icon={<PlusOutlined />} onClick={() => setShowUpload(true)}>
            上传文档
          </Button>
        </div>

        {showUpload && (
          <div className="mb-6">
            <Card
              title={
                <div className="flex justify-between items-center">
                  <span>上传文档到知识库</span>
                  <Button size="small" onClick={() => setShowUpload(false)}>
                    取消
                  </Button>
                </div>
              }
            >
              <div
                className="border-2 border-dashed border-[#dcdfe6] rounded-lg py-10 px-5 text-center cursor-pointer hover:border-[#1677ff] transition-colors mb-4"
                onClick={() => fileInputRef.current?.click()}
                onDragOver={(e) => e.preventDefault()}
                onDrop={handleDrop}
              >
                <input
                  ref={fileInputRef}
                  type="file"
                  accept=".pdf,.txt"
                  className="hidden"
                  onChange={handleFileSelect}
                />
                {!selectedFile ? (
                  <div className="text-[#909399]">
                    <UploadOutlined className="text-5xl mb-2" />
                    <p>点击或拖拽上传 PDF / TXT 文件</p>
                  </div>
                ) : (
                  <div className="flex items-center justify-center gap-3 text-[#333]">
                    <FileTextOutlined className="text-3xl" />
                    <span>{selectedFile.name}</span>
                    <Button
                      size="small"
                      onClick={(e) => {
                        e.stopPropagation()
                        clearFile()
                      }}
                    >
                      重新选择
                    </Button>
                  </div>
                )}
              </div>

              <div className="space-y-4">
                <div className="flex items-center gap-4">
                  <span className="w-20">文档类型</span>
                  <Radio.Group value={docType} onChange={(e) => setDocType(e.target.value)}>
                    <Radio value="reference_doc">参考资料</Radio>
                    <Radio value="excellent_resume">优秀简历</Radio>
                  </Radio.Group>
                </div>
                <div className="flex items-center gap-4">
                  <span className="w-20">分类</span>
                  <Input
                    value={category}
                    onChange={(e) => setCategory(e.target.value)}
                    placeholder="可选，如：前端开发、产品经理"
                    className="flex-1"
                  />
                </div>
                <div className="flex items-center gap-4">
                  <span className="w-20" />
                  <Button
                    type="primary"
                    disabled={!selectedFile || uploading}
                    loading={uploading}
                    onClick={handleUpload}
                  >
                    {uploading ? '上传中...' : '上传并索引'}
                  </Button>
                </div>
              </div>
            </Card>
          </div>
        )}

        {loading ? (
          <div className="flex flex-col items-center py-16 text-[#909399] gap-3">
            <Spin size="large" />
            <p>加载中...</p>
          </div>
        ) : documents.length === 0 ? (
          <Empty description="知识库为空，点击上方按钮上传文档" />
        ) : (
          <div className="space-y-3">
            {documents.map((doc) => (
              <Card key={doc.id} className="hover:shadow-md transition-shadow">
                <div className="flex flex-col gap-2">
                  <div className="flex items-center gap-2 text-[15px] font-medium text-[#333]">
                    <FileTextOutlined />
                    {doc.original_name}
                  </div>
                  <div className="flex items-center gap-3 text-xs text-[#999]">
                    <Tag color={doc.doc_type === 'excellent_resume' ? 'success' : 'default'}>
                      {doc.doc_type === 'excellent_resume' ? '优秀简历' : '参考资料'}
                    </Tag>
                    {doc.category && (
                      <span className="px-2 py-0.5 bg-[#f0f2f5] rounded">{doc.category}</span>
                    )}
                    <span>{formatSize(doc.file_size)}</span>
                    <span>{formatTime(doc.created_at)}</span>
                  </div>
                </div>
                <div className="flex items-center gap-4 mt-3 pt-3 border-t border-[#f0f0f0]">
                  <Switch
                    checked={doc.active === 1}
                    size="small"
                    onChange={(val) => handleToggle(doc.id, val)}
                  />
                  <Button
                    type="text"
                    danger
                    icon={<DeleteOutlined />}
                    onClick={() => handleDelete(doc.id)}
                  >
                    删除
                  </Button>
                </div>
              </Card>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
